/**
 * `/vs/:slug` — the head-to-head comparison pages, rendered from
 * `COMPARISONS` so the prose and the prerendered copies share one source.
 *
 * People look for "alternative to X" before they look for a category, so
 * these exist to answer that search honestly. The editorial rule lives with
 * the data (`src/models/comparisons.ts`): the other product's genuine
 * strengths are stated first and "when to pick theirs" has to be a real
 * recommendation. An unknown slug falls back to the index rather than a dead
 * end, since these URLs are public and will be mistyped.
 */

import { useStyletron } from 'baseui'
import {
  LabelLarge,
  LabelMedium,
  ParagraphMedium,
  ParagraphSmall,
} from 'baseui/typography'
import { ComparisonIndexPage } from '@/components/comparison-index-page'
import { ProsePage } from '@/components/prose-page'
import { comparisonBySlug, COMPARISONS } from '@/models/comparisons'
import { comparisonPath, COMPARISON_PATH_PREFIX } from '@/hooks/use-app-route'

export function ComparisonPage({ slug }: { slug: string }) {
  const [css, theme] = useStyletron()
  const comparison = comparisonBySlug(slug)

  const link = css({ color: theme.colors.contentPrimary })
  const section = css({
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  })

  // An unknown slug is a mistyped or retired URL, so show the hub rather than
  // a dead end — it's the same page `/vs` serves, and it explains the
  // category before offering the per-product pages.
  if (!comparison) return <ComparisonIndexPage />

  return (
    <ProsePage
      title={comparison.heading}
      documentTitle={comparison.documentTitle}
      lede={comparison.lede}
    >
      <section className={section}>
        <LabelLarge marginTop="0" marginBottom="0">
          What {comparison.name} does well
        </LabelLarge>
        <ul className={css({ paddingLeft: '1.1rem', margin: 0 })}>
          {comparison.strengths.map((s) => (
            <li key={s} className={css({ marginBottom: '6px' })}>
              <ParagraphMedium marginTop="0" marginBottom="0">
                {s}
              </ParagraphMedium>
            </li>
          ))}
        </ul>
        <ParagraphSmall
          marginTop="0"
          marginBottom="0"
          color={theme.colors.contentSecondary}
        >
          Their own description is on{' '}
          <a className={link} href={comparison.url} rel="noopener nofollow">
            their site
          </a>
          , which is the authority on what they currently do — anything here is
          a snapshot and can age.
        </ParagraphSmall>
      </section>

      <section className={section}>
        <LabelLarge marginTop="0" marginBottom="0">
          Where they differ
        </LabelLarge>
        <div
          className={css({
            display: 'flex',
            flexDirection: 'column',
            gap: '10px',
          })}
        >
          {comparison.differences.map((d) => (
            <div
              key={d.aspect}
              className={css({
                border: `1px solid ${theme.colors.borderOpaque}`,
                borderRadius: theme.borders.radius300,
                padding: '12px 14px',
                display: 'flex',
                flexDirection: 'column',
                gap: '4px',
              })}
            >
              <LabelMedium marginTop="0" marginBottom="0">
                {d.aspect}
              </LabelMedium>
              <ParagraphSmall marginTop="0" marginBottom="0">
                <strong>{comparison.name}:</strong> {d.theirs}
              </ParagraphSmall>
              <ParagraphSmall marginTop="0" marginBottom="0">
                <strong>Yes-Brainer:</strong> {d.ours}
              </ParagraphSmall>
            </div>
          ))}
        </div>
      </section>

      <section className={section}>
        <LabelLarge marginTop="0" marginBottom="0">
          Which to pick
        </LabelLarge>
        <ParagraphMedium marginTop="0" marginBottom="0">
          <strong>Pick {comparison.name} if:</strong> {comparison.pickTheirs}
        </ParagraphMedium>
        <ParagraphMedium marginTop="0" marginBottom="0">
          <strong>Pick Yes-Brainer if:</strong> {comparison.pickOurs}
        </ParagraphMedium>
        <ParagraphSmall
          marginTop="0"
          marginBottom="0"
          color={theme.colors.contentSecondary}
        >
          Whichever you use, every answer either one shows is generated by an
          AI model and can be confidently wrong — seeing several models agree
          is not evidence that they are right.
        </ParagraphSmall>
      </section>

      <section className={section}>
        <LabelLarge marginTop="0" marginBottom="0">
          Other comparisons
        </LabelLarge>
        <ParagraphSmall marginTop="0" marginBottom="0">
          <a className={link} href={COMPARISON_PATH_PREFIX}>
            How Yes-Brainer compares
          </a>{' '}
          — the category-level view: hosted council products, the open-source
          llm-council forks, and multi-model chat aggregators.
        </ParagraphSmall>
        <ul className={css({ paddingLeft: '1.1rem', margin: 0 })}>
          {COMPARISONS.filter((c) => c.slug !== comparison.slug).map((c) => (
            <li key={c.slug} className={css({ marginBottom: '6px' })}>
              <a className={link} href={comparisonPath(c.slug)}>
                Yes-Brainer vs {c.name}
              </a>
            </li>
          ))}
        </ul>
      </section>
    </ProsePage>
  )
}
