/**
 * The SEO route manifest — the single source of truth for **which paths get a
 * prerendered HTML file** and **what goes into `sitemap.xml`**. Consumed by
 * `scripts/prerender.mjs` at build time; nothing imports it at runtime.
 *
 * Why a manifest at all: the app is a client-rendered SPA, so a crawler that
 * doesn't execute JS sees one shell for every URL. Vite emits a single
 * `index.html`; this manifest is the list of routes that deserve their own
 * file with their own `<title>`, description, canonical and OG/Twitter tags —
 * plus, for content routes, real text inside `#root` so a non-JS crawler
 * (most AI answer engines, most link-preview bots) has something to read.
 * `createRoot` clears `#root`'s children on mount, so that prerendered text
 * is replaced by the real app the moment React boots — same content, no
 * hydration contract, nothing hidden from users that a crawler can see.
 *
 * **Every `path` here must also be a real route in the app** (see
 * `src/hooks/use-app-route.ts`). A prerendered file without a matching client
 * route would render the shell's fallback after React mounts — a visible
 * content swap. Adding a page means touching both.
 *
 * The `/vs/*` entries are derived from `src/models/comparisons.json`, which
 * the app reads too, so the page and its prerendered copy cannot disagree.
 *
 * Per-user routes (`/council/:id`, `/settings`) are deliberately absent: they
 * are client state, not documents. They fall through to `dist/404.html`,
 * which Pages serves with an HTTP 404 status so crawlers skip them.
 */

import { readdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { slugify } from './slugify.mjs'

export const SITE_ORIGIN = 'https://yesbrainer.ai'

/** Escape a string for use as HTML text content. */
export function text(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
}

/**
 * `/` needs no rewrite — Vite's `index.html` *is* the home document, and its
 * head is already home-specific. It's listed only so the sitemap generator
 * has one place to look.
 */
export const HOME_ROUTE = { path: '/' }

const comparisons = JSON.parse(
  readFileSync(
    fileURLToPath(new URL('../src/models/comparisons.json', import.meta.url)),
    'utf8',
  ),
)

const hub = JSON.parse(
  readFileSync(
    fileURLToPath(
      new URL('../src/models/comparison-hub.json', import.meta.url),
    ),
    'utf8',
  ),
)

/** `<h1>` + lede, the opening of every prerendered body. */
function heroHtml(title, lede) {
  return `<h1>${text(title)}</h1><p class="pr__lede">${text(lede)}</p>`
}

/**
 * Every prerendered body ends with a way onward. Without it these pages are
 * dead ends for the two audiences that only ever see this HTML: a crawler
 * that doesn't run JS (no path to the rest of the site) and a visitor whose
 * JS hasn't loaded yet (no path to the app). One link fixes both.
 */
const HOME_LINK =
  '<p class="pr__note"><a href="/">Yes-Brainer</a> — ask several AI models ' +
  'one question and see where they disagree. Free and open source; no ' +
  'account, and you bring your own API keys.</p>'

/** The caveat every page carrying model output has to end on. */
const AI_CAVEAT =
  'Every answer Yes-Brainer shows is generated by an AI model and can be ' +
  'confidently wrong. Seeing several models agree is not evidence that they ' +
  'are right — the app shows the spread; the judgment stays yours.'

function comparisonBody(c) {
  const strengths = c.strengths.map((s) => `<li>${text(s)}</li>`).join('')
  const differences = c.differences
    .map(
      (d) =>
        `<h3>${text(d.aspect)}</h3>` +
        `<p><strong>${text(c.name)}:</strong> ${text(d.theirs)}</p>` +
        `<p><strong>Yes-Brainer:</strong> ${text(d.ours)}</p>`,
    )
    .join('')
  // The cluster's internal links have to exist *here*, not just in the React
  // component: a crawler that doesn't run JS sees only this HTML, and without
  // them each comparison is an island the hub points at but nothing points
  // back from. Mirrors what ComparisonPage renders.
  const siblings = comparisons
    .filter((o) => o.slug !== c.slug)
    .map(
      (o) =>
        `<li><a href="/vs/${o.slug}">Yes-Brainer vs ${text(o.name)}</a></li>`,
    )
    .join('')

  return (
    heroHtml(c.heading, c.lede) +
    `<h2>What ${text(c.name)} does well</h2><ul>${strengths}</ul>` +
    `<h2>Where they differ</h2>${differences}` +
    `<h2>Which to pick</h2>` +
    `<p><strong>Pick ${text(c.name)} if:</strong> ${text(c.pickTheirs)}</p>` +
    `<p><strong>Pick Yes-Brainer if:</strong> ${text(c.pickOurs)}</p>` +
    `<h2>Other comparisons</h2>` +
    `<p><a href="/vs">How Yes-Brainer compares</a> — the category-level view: ` +
    `hosted council products, the open-source llm-council forks, and ` +
    `multi-model chat aggregators.</p>` +
    `<ul>${siblings}</ul>` +
    `<p class="pr__note">${text(AI_CAVEAT)}</p>` +
    HOME_LINK
  )
}

const PRIVATE_TITLE = 'No account, no server — Yes-Brainer'
const PRIVATE_DESCRIPTION =
  'Yes-Brainer asks several AI models one question and shows where their ' +
  'answers differ. It runs in your browser: no sign-up, no server run by ' +
  'this project holds your conversations, and you bring your own API keys.'

const PRIVATE_BODY =
  heroHtml(
    'An AI chat with no account, no server, and your own API keys',
    'Yes-Brainer asks several AI models one question and shows you where their answers differ. It runs entirely in your browser: there is no sign-up, and no server run by this project holds your conversations.',
  ) +
  '<h2>No account</h2><p>There is no sign-up form, no email, no password and no profile — because there is no backend to hold one. Recorded demo councils can be read without any API key at all.</p>' +
  '<h2>No server of ours in the middle</h2><p>The app is a static bundle of HTML, CSS and JavaScript. The network traffic from your browser is calls to the model providers you chose, with your keys — direct to the vendor for the native adapters, and through OpenRouter’s gateway first if you use OpenRouter, which is what its one-key-many-vendors convenience buys.</p>' +
  '<p>There is also one cookieless counter on the official site. It records the route pattern, screen size, language, the referrer that brought you, and counts of a few feature-level actions — that a feature was used, not what was in it. No cookies, no client-side identifier.</p>' +
  '<ul>' +
  '<li><strong>API keys</strong> — your browser’s localStorage, plaintext, per device. Sent to the provider you point them at, and only when you send a turn.</li>' +
  '<li><strong>Conversations</strong> — your browser’s IndexedDB. No copy is synced or stored anywhere else.</li>' +
  '<li><strong>Settings</strong> — localStorage. Nobody else sees them.</li>' +
  '<li><strong>Provider API calls</strong> — direct browser to provider over TLS.</li>' +
  '</ul>' +
  '<h2>Your own API keys</h2><p>Bring keys for the providers you want — Anthropic, OpenAI, Google, Groq, OpenRouter, or a local Ollama that needs no key — and pay those providers directly. No subscription, no paywall on the app itself. Two duties stay yours: check the address bar reads yesbrainer.ai before pasting a key, and use a dedicated key with a spending limit set in your provider’s console.</p>' +
  '<h2>What this does not do</h2><p>Keeping data on your device moves the risk rather than removing it. Anything with access to your browser profile can read what is stored there, losing the device loses the data on it, and browsers can evict site storage. Your prompts still travel to whichever providers you point the app at, under their terms. The software is provided as-is, with no warranty.</p>' +
  `<p class="pr__note">${text(AI_CAVEAT)}</p>` +
  HOME_LINK

/**
 * Routes that get `dist/<file>` with a rewritten head.
 *
 * - `path`        — URL path, no trailing slash. Must match a client route.
 * - `file`        — output filename in `dist/`. Use `<name>.html`, NOT
 *                   `<name>/index.html`: Pages serves the extensionless
 *                   lookup with a 200, while the directory form 301s to a
 *                   trailing slash.
 * - `title`       — `<title>` and `og:title`/`twitter:title`.
 * - `description` — meta description + `og:`/`twitter:` description.
 * - `body`        — optional HTML injected into `#root` in place of the boot
 *                   splash. Plain semantic markup only; it is visible for the
 *                   pre-mount instant, so keep it readable.
 * - `jsonLd`      — optional object replacing the default `WebApplication`
 *                   structured-data block.
 */
export const CONTENT_ROUTES = [
  {
    path: '/about',
    file: 'about.html',
    // Same string AboutPage sets as document.title on in-app navigation
    // (src/components/about-page.tsx) — keep the two in sync.
    title: 'About Yes-Brainer — a council of AI models',
    description:
      'What Yes-Brainer is and how to start: ask one question and let several ' +
      'AI models answer in parallel, debate to consensus, or judge each other ' +
      'for a single verdict. No accounts, no server — keys stay in your ' +
      'browser and go straight to the providers you choose.',
  },
  {
    path: '/private',
    file: 'private.html',
    // Mirrors PrivatePage's documentTitle (src/components/private-page.tsx).
    title: PRIVATE_TITLE,
    description: PRIVATE_DESCRIPTION,
    body: PRIVATE_BODY,
  },
  {
    path: '/vs',
    file: 'vs.html',
    // Mirrors ComparisonIndexPage's documentTitle, which reads the same JSON.
    title: hub.documentTitle,
    description: hub.description,
    body:
      heroHtml(hub.heading, hub.lede) +
      hub.categories
        .map(
          (c) =>
            `<h2>${text(c.name)}</h2>` +
            `<p class="pr__note">${text(c.examples)}</p>` +
            `<p>${text(c.body)}</p>`,
        )
        .join('') +
      `<h2>Where Yes-Brainer sits</h2><p>${text(hub.position)}</p>` +
      `<h2>Head to head</h2><ul>${comparisons
        .map(
          (c) =>
            `<li><a href="/vs/${c.slug}">Yes-Brainer vs ${text(c.name)}</a> — ${text(c.lede)}</li>`,
        )
        .join('')}</ul>` +
      `<p class="pr__note">${text(hub.closing)} ${text(
        hub.invitation.before + hub.invitation.linkText + hub.invitation.after,
      )}</p>` +
      `<p class="pr__note">${text(hub.note)}</p>` +
      HOME_LINK,
  },
  ...comparisons.map((c) => ({
    path: `/vs/${c.slug}`,
    // `/vs/<slug>` needs `dist/vs/<slug>.html`; the directory is created by
    // the writer.
    file: `vs/${c.slug}.html`,
    title: c.documentTitle,
    description: c.description,
    body: comparisonBody(c),
  })),
]

// ---- demo councils ----

/**
 * The seeded demo councils are the only council content that is identical for
 * every visitor, needs no API key to read, and exists nowhere else on the
 * web — so they get public, indexable permalinks. The app resolves the same
 * slugs at runtime (`/demo/:slug`, see `src/app.tsx`).
 *
 * Deliberately **no QAPage / Question structured data**: Google scopes that
 * type to pages where *people* submit answers, and these answers are model
 * output. Marking them up as a community Q&A to chase a rich result would be
 * exactly the kind of structured-data misuse that earns a manual action, so
 * these pages inherit the shell's `WebApplication` block instead.
 *
 * Answer text is excerpted rather than reproduced in full — this body is a
 * pre-mount bridge, not a second copy of the app. Less than the app shows is
 * fine; *different* from what the app shows would not be.
 */
const DEMO_DIR = fileURLToPath(
  new URL('../src/data/demo-councils', import.meta.url),
)
/** Longest answer excerpt per model in the prerendered body. */
const EXCERPT_CHARS = 700

function councilsFromFile(fileData) {
  return Array.isArray(fileData?.councils) ? fileData.councils : [fileData]
}

/** `anthropic:claude-opus-4-8` → `claude-opus-4-8 (anthropic)`. */
function modelLabel(modelId) {
  if (typeof modelId !== 'string') return 'a model'
  const [provider, ...rest] = modelId.split(':')
  const model = rest.join(':')
  return model ? `${model} (${provider})` : modelId
}

/** Strip markdown to a readable plain-text excerpt. */
function excerpt(markdown) {
  const plain = String(markdown ?? '')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/[#*_`>|]/g, '')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/\s+/g, ' ')
    .trim()
  return plain.length > EXCERPT_CHARS
    ? `${plain.slice(0, EXCERPT_CHARS).trimEnd()}…`
    : plain
}

function demoRoute(council) {
  const turn = council.turns?.[0]
  const question = turn?.userMsg
  if (!council.title || !question) return null

  const slug = slugify(council.title)
  if (!slug) return null

  // One entry per seat: the model's *last* contribution in the turn, so a
  // consensus council shows the position it settled on rather than its
  // opening one.
  const bySeat = new Map()
  for (const event of turn.events ?? []) {
    if (event.roleType !== 'participant' && event.roleType !== 'reanswer') {
      continue
    }
    bySeat.set(event.seatId, event)
  }

  const answers = [...bySeat.values()]
    .map(
      (e) =>
        `<h3>${text(modelLabel(e.modelId))}</h3><p>${text(excerpt(e.output))}</p>`,
    )
    .join('')

  // The referee's closing word, whichever role played it.
  const closing = [...(turn.events ?? [])]
    .reverse()
    .find((e) => e.roleType === 'mediator' || e.roleType === 'judge')
  const closingHtml = closing
    ? `<h2>How it ended</h2><p>${text(
        excerpt(closing.mediator?.roundDigest?.summary ?? closing.output),
      )}</p>`
    : ''

  const lede = `A recorded Yes-Brainer council: ${bySeat.size} AI models answering one question, and where they differed. Readable without an API key.`

  return {
    path: `/demo/${slug}`,
    file: `demo/${slug}.html`,
    title: `${council.title} — a council of AI models compared`,
    description: excerpt(question).slice(0, 180),
    body:
      heroHtml(council.title, lede) +
      `<h2>The question</h2><blockquote>${text(excerpt(question))}</blockquote>` +
      `<h2>What each model said</h2>${answers}` +
      closingHtml +
      `<p class="pr__note">${text(AI_CAVEAT)}</p>` +
      HOME_LINK,
  }
}

export const DEMO_ROUTES = readdirSync(DEMO_DIR)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .flatMap((f) =>
    councilsFromFile(JSON.parse(readFileSync(`${DEMO_DIR}/${f}`, 'utf8'))),
  )
  .map(demoRoute)
  .filter((r) => r !== null)

// Two demos whose titles slugify the same would collide silently and badly:
// the second would overwrite the first's HTML file, the sitemap would list
// the URL twice, and the app's `councils.find(...)` would open whichever
// sorted first — a published page showing content other than the one it was
// generated from. Cheap to detect, so detect it.
{
  const seen = new Set()
  const clashes = DEMO_ROUTES.map((r) => r.path).filter(
    (p) => seen.size === seen.add(p).size,
  )
  if (clashes.length > 0) {
    throw new Error(
      `[seo-routes] demo council titles collide on slug: ${[
        ...new Set(clashes),
      ].join(', ')} — rename one in src/data/demo-councils/.`,
    )
  }
}

/** Every path that belongs in `sitemap.xml`, in document order. */
export function sitemapPaths(extraRoutes = []) {
  return [
    HOME_ROUTE.path,
    ...CONTENT_ROUTES.map((r) => r.path),
    ...extraRoutes.map((r) => r.path),
  ]
}
