// AUTO-GENERATED by `npm run update-models-catalog` — do not edit by hand.
// Source: OpenRouter https://openrouter.ai/api/v1/models. The native (direct-routed) providers live in
// registry.ts; this file is only the curated OpenRouter slice. `registry.ts`
// spreads these in and adds `defaultSystemPrompt`.

import type { ModelEntry } from './registry'

export const OPENROUTER_MODELS: Omit<ModelEntry, 'defaultSystemPrompt'>[] = [
  {
    modelId: 'openrouter:cohere/command-a',
    label: 'Cohere Command A',
    provider: 'openrouter',
    providerModelId: 'cohere/command-a',
    tier: 'paid',
    country: 'Canada',
    developer: 'Cohere',
    contextWindow: 256000,
    capabilities: { tools: false, vision: false, reasoning: false },
  },
  {
    modelId: 'openrouter:deepseek/deepseek-v4-pro',
    label: 'DeepSeek DeepSeek V4 Pro',
    provider: 'openrouter',
    providerModelId: 'deepseek/deepseek-v4-pro',
    tier: 'paid',
    country: 'China',
    developer: 'DeepSeek',
    contextWindow: 1048576,
    capabilities: { tools: true, vision: false, reasoning: true },
  },
  {
    modelId: 'openrouter:mistralai/mistral-large-2512',
    label: 'Mistral Mistral Large 3 2512',
    provider: 'openrouter',
    providerModelId: 'mistralai/mistral-large-2512',
    tier: 'paid',
    country: 'France',
    developer: 'Mistral AI',
    contextWindow: 262144,
    capabilities: { tools: true, vision: true, reasoning: false },
  },
  {
    modelId: 'openrouter:moonshotai/kimi-k2.6',
    label: 'MoonshotAI Kimi K2.6',
    provider: 'openrouter',
    providerModelId: 'moonshotai/kimi-k2.6',
    tier: 'paid',
    country: 'China',
    developer: 'Moonshot AI',
    contextWindow: 262144,
    capabilities: { tools: true, vision: true, reasoning: true },
  },
  {
    modelId: 'openrouter:qwen/qwen3.7-max',
    label: 'Qwen Qwen3.7 Max',
    provider: 'openrouter',
    providerModelId: 'qwen/qwen3.7-max',
    tier: 'paid',
    country: 'China',
    developer: 'Alibaba',
    contextWindow: 1000000,
    capabilities: { tools: true, vision: false, reasoning: true },
  },
  {
    modelId: 'openrouter:x-ai/grok-4.5',
    label: 'xAI Grok 4.5',
    provider: 'openrouter',
    providerModelId: 'x-ai/grok-4.5',
    tier: 'paid',
    country: 'USA',
    developer: 'xAI',
    contextWindow: 500000,
    capabilities: { tools: true, vision: true, reasoning: true },
  },
]
